Mms: fix crash when replying on MSim
Shutting down VM
FATAL EXCEPTION: main
Process: com.android.mms, PID: 9276
android.util.AndroidRuntimeException: requestFeature() must be called before adding content
	at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:301)
	at com.android.internal.app.AlertController.installContent(AlertController.java:231)
	at android.app.AlertDialog.onCreate(AlertDialog.java:356)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:373)
	at android.app.Dialog.show(Dialog.java:274)
	at com.android.mms.ui.ComposeMessageActivity.LaunchMsimDialog(ComposeMessageActivity.java:916)
	at com.android.mms.ui.ComposeMessageActivity.sendMsimMessage(ComposeMessageActivity.java:926)
	at com.android.mms.ui.ComposeMessageActivity.confirmSendMessageIfNeeded(ComposeMessageActivity.java:1000)
	at com.android.mms.ui.ComposeMessageActivity.onClick(ComposeMessageActivity.java:4123)
	at android.view.View.performClick(View.java:4756)
	at android.view.View$PerformClick.run(View.java:19749)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5223)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

Change-Id: I8c279fb63fca8510e3022b2a7ba9e42e66843541
(cherry picked from commit 5980a411d8ce561e29055111a4170b269268ce8b)